#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# load zshrc files
ZSHRCS=($HOME/.zshrc.*)
for f in ${ZSHRCS}; do
    if [ -f $f ]; then
        source $f
    fi
done

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /Users/yukichi/go/bin/mc mc
